#!/bin/bash
# QUICK FIX: Production Database Connection Pool Issue

echo "=========================================="
echo "VOCABVAULT - DB CONNECTION FIX"
echo "=========================================="
echo ""
echo "ISSUE: App crashes after login in production"
echo "CAUSE: PgBouncer connection pool exhausted (max 15)"
echo ""
echo "=========================================="
echo "IMMEDIATE ACTION REQUIRED:"
echo "=========================================="
echo ""
echo "1. UPDATE LOCAL ENVIRONMENT"
echo "   File: .env.local"
echo "   Find: DATABASE_URL=..."
echo ""
echo "   CHANGE THIS:"
echo "   postgres://...com:6543/postgres?pgbouncer=true&prepared_statements=false"
echo ""
echo "   TO THIS:"
echo "   postgres://...com:6543/postgres?pgbouncer=true&prepared_statements=false&connection_limit=30"
echo ""
echo ""
echo "2. UPDATE VERCEL PRODUCTION"
echo "   Go to: https://vercel.com/dashboard"
echo "   → Select VocabVault project"
echo "   → Settings > Environment Variables"
echo "   → Find: DATABASE_URL"
echo "   → Add: &connection_limit=30 to the URL (same as above)"
echo "   → Save"
echo ""
echo ""
echo "3. REDEPLOY VERCEL"
echo "   Go to: https://vercel.com/dashboard"
echo "   → Select VocabVault project"
echo "   → Deployments"
echo "   → Click \"Redeploy\" on latest deployment"
echo ""
echo ""
echo "4. TEST LOGIN"
echo "   Wait 3 min for deployment"
echo "   → Open production app"
echo "   → Try logging in"
echo "   → Verify dashboard loads without crashing"
echo ""
echo "=========================================="
echo "EXACT DATABASE_URL VALUE:"
echo "=========================================="
echo ""
echo "postgresql://postgres.ionoednowlfejuanjpqu:vocabvault1@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&prepared_statements=false&connection_limit=30"
echo ""
echo "=========================================="
echo ""
echo "If still having issues after 30 mins, check:"
echo "  1. Vercel Logs: Settings > Functions > Logs"
echo "  2. Search for: EMAXCONNSESSION"
echo "  3. Check Prisma connection state"
